# -*- mode: ruby -*-
# vi: set ft=ruby :

node = JSON.parse(File.read(File.dirname(__FILE__) + "/node.json"))

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :delta do |x|
    x.vm.box = "ubuntu/trusty64"
    x.vm.hostname = node['vm_name']

    if node['provider'] == 'virtualbox'
      x.vm.network :private_network, ip: node['network']['ip']
      x.vm.network :forwarded_port, guest: 80, host: node['network']['forward_80_port']
      x.vm.network :forwarded_port, guest: 22, host: node['network']['forward_22_port']

      x.vm.provider :virtualbox do |v|
        v.name = node['vm_name']
      end
    end

    if node['provider'] == 'aws'
      x.vm.provider :aws do |aws, override|
        aws.access_key_id = node['aws']['access_key_id']
        aws.secret_access_key = node['aws']['secret_access_key']
        aws.keypair_name = node['aws']['keypair_name']
        aws.ami = node['aws']['ami']
        aws.region = node['aws']['region']
        aws.instance_type = node['aws']['instance_type']
        aws.security_groups = node['aws']['security_groups']
        aws.elastic_ip = node['aws']['elastic_ip']

        override.vm.box = "dummy"
        override.ssh.username = node['ssh_username']
        override.ssh.private_key_path = node['aws']['private_key_path']
      end
    end
  end

  config.vm.provision :chef_solo do |chef|
    if node['chef_json']['web_server']['provider'] == 'aws'
      chef.synced_folder_type = "rsync"
    end
    
    chef.roles_path = "../chef/roles"
    chef.cookbooks_path = ["../chef/cookbooks", "../chef/patron-cookbooks"]
    chef.data_bags_path = "../chef/data_bags"
    
    case node['chef_json']['web_server']['type']
    when 'unicorn', 'basic'
      role = 'ror'
    when 'php'
      role = 'lamp'
    else
      raise 'Improper web_server.type'
    end
    
    chef.add_role role

    # Install Ruby and Bundler
    chef.json = node['chef_json']
  end
end
